export const palmeraModuleAbi = [{ "inputs": [{ "internalType": "address", "name": "authorityAddress", "type": "address" }, { "internalType": "uint256", "name": "maxDepthTreeLimitInitial", "type": "uint256" }], "stateMutability": "nonpayable", "type": "constructor" }, { "inputs": [], "name": "AddresNotAllowed", "type": "error" }, { "inputs": [], "name": "AddressDenied", "type": "error" }, { "inputs": [{ "internalType": "uint256", "name": "children", "type": "uint256" }], "name": "CannotRemoveSafeBeforeRemoveChild", "type": "error" }, { "inputs": [], "name": "DenyHelpersDisabled", "type": "error" }, { "inputs": [], "name": "EmptyName", "type": "error" }, { "inputs": [], "name": "InvalidAddressProvided", "type": "error" }, { "inputs": [], "name": "InvalidLimit", "type": "error" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "InvalidRootSafe", "type": "error" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "InvalidSafe", "type": "error" }, { "inputs": [], "name": "InvalidSafeId", "type": "error" }, { "inputs": [], "name": "ListEmpty", "type": "error" }, { "inputs": [], "name": "NotAuthorizedAddOwnerWithThreshold", "type": "error" }, { "inputs": [], "name": "NotAuthorizedAsNotRootOrSuperSafe", "type": "error" }, { "inputs": [], "name": "NotAuthorizedDisconnectChildrenSafe", "type": "error" }, { "inputs": [], "name": "NotAuthorizedExecOnBehalf", "type": "error" }, { "inputs": [], "name": "NotAuthorizedRemoveOwner", "type": "error" }, { "inputs": [], "name": "NotAuthorizedSetRoleAnotherTree", "type": "error" }, { "inputs": [], "name": "NotAuthorizedUpdateNonChildrenSafe", "type": "error" }, { "inputs": [], "name": "NotAuthorizedUpdateNonSuperSafe", "type": "error" }, { "inputs": [], "name": "NotAuthorizedUpdateSafeToOtherOrg", "type": "error" }, { "inputs": [], "name": "NotPermittedReceiveEther", "type": "error" }, { "inputs": [{ "internalType": "bytes32", "name": "safe", "type": "bytes32" }], "name": "OrgAlreadyRegistered", "type": "error" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }], "name": "OrgNotRegistered", "type": "error" }, { "inputs": [], "name": "OwnerAlreadyExists", "type": "error" }, { "inputs": [], "name": "OwnerNotFound", "type": "error" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "PreviewModuleNotFound", "type": "error" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "SafeAlreadyRegistered", "type": "error" }, { "inputs": [], "name": "SafeAlreadyRemoved", "type": "error" }, { "inputs": [{ "internalType": "uint256", "name": "safe", "type": "uint256" }], "name": "SafeIdNotRegistered", "type": "error" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "SafeNotRegistered", "type": "error" }, { "inputs": [{ "internalType": "enum DataTypes.Role", "name": "role", "type": "uint8" }], "name": "SetRoleForbidden", "type": "error" }, { "inputs": [{ "internalType": "uint256", "name": "limit", "type": "uint256" }], "name": "TreeDepthLimitReached", "type": "error" }, { "inputs": [], "name": "TxExecutionModuleFailed", "type": "error" }, { "inputs": [], "name": "TxOnBehalfExecutedFailed", "type": "error" }, { "inputs": [], "name": "UserAlreadyOnList", "type": "error" }, { "inputs": [], "name": "ZeroAddressProvided", "type": "error" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "address[]", "name": "users", "type": "address[]" }], "name": "AddedToList", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "contract Authority", "name": "newAuthority", "type": "address" }], "name": "AuthorityUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }], "name": "DroppedFromList", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "rootSafeId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "updater", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "oldLimit", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "newLimit", "type": "uint256" }], "name": "NewLimitLevel", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "creator", "type": "address" }, { "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "OrganisationCreated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "newOwner", "type": "address" }], "name": "OwnerUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "newIdRootSafe", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "creator", "type": "address" }, { "indexed": false, "internalType": "address", "name": "newRootSafe", "type": "address" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "RootSafeCreated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "newIdRootSafe", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "updater", "type": "address" }, { "indexed": false, "internalType": "address", "name": "newRootSafe", "type": "address" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "RootSafePromoted", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "safeCreated", "type": "uint256" }, { "indexed": false, "internalType": "address", "name": "lead", "type": "address" }, { "indexed": true, "internalType": "address", "name": "creator", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "superSafe", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "SafeCreated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "safeId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "safe", "type": "address" }, { "indexed": false, "internalType": "address", "name": "disconnector", "type": "address" }], "name": "SafeDisconnected", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "safeRemoved", "type": "uint256" }, { "indexed": false, "internalType": "address", "name": "lead", "type": "address" }, { "indexed": true, "internalType": "address", "name": "remover", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "superSafe", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "SafeRemoved", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "safeUpdated", "type": "uint256" }, { "indexed": false, "internalType": "address", "name": "lead", "type": "address" }, { "indexed": true, "internalType": "address", "name": "updater", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "oldSuperSafe", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "newSuperSafe", "type": "uint256" }], "name": "SafeSuperUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "address", "name": "executor", "type": "address" }, { "indexed": false, "internalType": "address", "name": "superSafe", "type": "address" }, { "indexed": true, "internalType": "address", "name": "target", "type": "address" }, { "indexed": false, "internalType": "bool", "name": "result", "type": "bool" }], "name": "TxOnBehalfExecuted", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "indexed": true, "internalType": "uint256", "name": "rootSafeId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "remover", "type": "address" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }], "name": "WholeTreeRemoved", "type": "event" }, { "stateMutability": "nonpayable", "type": "fallback" }, { "inputs": [], "name": "NAME", "outputs": [{ "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "VERSION", "outputs": [{ "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "ownerAdded", "type": "address" }, { "internalType": "uint256", "name": "threshold", "type": "uint256" }, { "internalType": "address", "name": "targetSafe", "type": "address" }, { "internalType": "bytes32", "name": "org", "type": "bytes32" }], "name": "addOwnerWithThreshold", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "superSafeId", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }], "name": "addSafe", "outputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address[]", "name": "users", "type": "address[]" }], "name": "addToList", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "allowFeature", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "authority", "outputs": [{ "internalType": "contract Authority", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "newRootSafe", "type": "address" }, { "internalType": "string", "name": "name", "type": "string" }], "name": "createRootSafe", "outputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "denyFeature", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "depthTreeLimit", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "disableDenyHelper", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "disconnectSafe", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "domainSeparator", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "user", "type": "address" }], "name": "dropFromList", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "enableAllowlist", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "enableDenylist", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "superSafe", "type": "address" }, { "internalType": "address", "name": "targetSafe", "type": "address" }, { "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "value", "type": "uint256" }, { "internalType": "bytes", "name": "data", "type": "bytes" }, { "internalType": "enum Enum.Operation", "name": "operation", "type": "uint8" }, { "internalType": "uint256", "name": "_nonce", "type": "uint256" }], "name": "encodeTransactionData", "outputs": [{ "internalType": "bytes", "name": "", "type": "bytes" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "superSafe", "type": "address" }, { "internalType": "address", "name": "targetSafe", "type": "address" }, { "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "value", "type": "uint256" }, { "internalType": "bytes", "name": "data", "type": "bytes" }, { "internalType": "enum Enum.Operation", "name": "operation", "type": "uint8" }, { "internalType": "bytes", "name": "signatures", "type": "bytes" }], "name": "execTransactionOnBehalf", "outputs": [{ "internalType": "bool", "name": "result", "type": "bool" }], "stateMutability": "payable", "type": "function" }, { "inputs": [], "name": "getChainId", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "getOrgBySafe", "outputs": [{ "internalType": "bytes32", "name": "orgSafe", "type": "bytes32" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "getOrgHashBySafe", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "wallet", "type": "address" }], "name": "getPrevUser", "outputs": [{ "internalType": "address", "name": "prevUser", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "getRootSafe", "outputs": [{ "internalType": "uint256", "name": "rootSafeId", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "getSafeAddress", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "safe", "type": "address" }], "name": "getSafeIdBySafe", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "getSafeInfo", "outputs": [{ "internalType": "enum DataTypes.Tier", "name": "", "type": "uint8" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "address", "name": "", "type": "address" }, { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256[]", "name": "", "type": "uint256[]" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "superSafe", "type": "address" }, { "internalType": "address", "name": "targetSafe", "type": "address" }, { "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "value", "type": "uint256" }, { "internalType": "bytes", "name": "data", "type": "bytes" }, { "internalType": "enum Enum.Operation", "name": "operation", "type": "uint8" }, { "internalType": "uint256", "name": "_nonce", "type": "uint256" }], "name": "getTransactionHash", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "caller", "type": "address" }, { "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "targetSafe", "type": "address" }], "name": "hasNotPermissionOverTarget", "outputs": [{ "internalType": "bool", "name": "hasNotPermission", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "indexId", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "name": "indexSafe", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "superSafeId", "type": "uint256" }], "name": "isLimitLevel", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }, { "internalType": "address", "name": "wallet", "type": "address" }], "name": "isListed", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "org", "type": "bytes32" }], "name": "isOrgRegistered", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "rootSafeId", "type": "uint256" }, { "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "isPendingRemove", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "root", "type": "address" }, { "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "isRootSafeOf", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "isSafe", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }, { "internalType": "address", "name": "user", "type": "address" }], "name": "isSafeLead", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "safe", "type": "address" }], "name": "isSafeRegistered", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "superSafeId", "type": "uint256" }, { "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "isSuperSafe", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "superSafeId", "type": "uint256" }, { "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "isTreeMember", "outputs": [{ "internalType": "bool", "name": "isMember", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "listCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "nonce", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "promoteRoot", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "string", "name": "orgName", "type": "string" }], "name": "registerOrg", "outputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "prevOwner", "type": "address" }, { "internalType": "address", "name": "ownerRemoved", "type": "address" }, { "internalType": "uint256", "name": "threshold", "type": "uint256" }, { "internalType": "address", "name": "targetSafe", "type": "address" }, { "internalType": "bytes32", "name": "org", "type": "bytes32" }], "name": "removeOwner", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }], "name": "removeSafe", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "removeWholeTree", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "name": "safes", "outputs": [{ "internalType": "enum DataTypes.Tier", "name": "tier", "type": "uint8" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "address", "name": "lead", "type": "address" }, { "internalType": "address", "name": "safe", "type": "address" }, { "internalType": "uint256", "name": "superSafe", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "contract Authority", "name": "newAuthority", "type": "address" }], "name": "setAuthority", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "newOwner", "type": "address" }], "name": "setOwner", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "enum DataTypes.Role", "name": "role", "type": "uint8" }, { "internalType": "address", "name": "user", "type": "address" }, { "internalType": "uint256", "name": "safeId", "type": "uint256" }, { "internalType": "bool", "name": "enabled", "type": "bool" }], "name": "setRole", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "newLimit", "type": "uint256" }], "name": "updateDepthTreeLimit", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "safeId", "type": "uint256" }, { "internalType": "uint256", "name": "newSuperId", "type": "uint256" }], "name": "updateSuper", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "stateMutability": "payable", "type": "receive" }]

export const safeAbi = [
    { inputs: [], stateMutability: "nonpayable", type: "constructor" },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
            },
        ],
        name: "AddedOwner",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "bytes32",
                name: "approvedHash",
                type: "bytes32",
            },
            {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
            },
        ],
        name: "ApproveHash",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "handler",
                type: "address",
            },
        ],
        name: "ChangedFallbackHandler",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "guard",
                type: "address",
            },
        ],
        name: "ChangedGuard",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "threshold",
                type: "uint256",
            },
        ],
        name: "ChangedThreshold",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "module",
                type: "address",
            },
        ],
        name: "DisabledModule",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "module",
                type: "address",
            },
        ],
        name: "EnabledModule",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "bytes32",
                name: "txHash",
                type: "bytes32",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "payment",
                type: "uint256",
            },
        ],
        name: "ExecutionFailure",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "module",
                type: "address",
            },
        ],
        name: "ExecutionFromModuleFailure",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "module",
                type: "address",
            },
        ],
        name: "ExecutionFromModuleSuccess",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "bytes32",
                name: "txHash",
                type: "bytes32",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "payment",
                type: "uint256",
            },
        ],
        name: "ExecutionSuccess",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
            },
        ],
        name: "RemovedOwner",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "SafeReceived",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "initiator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "threshold",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "initializer",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "fallbackHandler",
                type: "address",
            },
        ],
        name: "SafeSetup",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "bytes32",
                name: "msgHash",
                type: "bytes32",
            },
        ],
        name: "SignMsg",
        type: "event",
    },
    { stateMutability: "nonpayable", type: "fallback" },
    {
        inputs: [],
        name: "VERSION",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "_threshold", type: "uint256" },
        ],
        name: "addOwnerWithThreshold",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "hashToApprove", type: "bytes32" },
        ],
        name: "approveHash",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "", type: "address" },
            { internalType: "bytes32", name: "", type: "bytes32" },
        ],
        name: "approvedHashes",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "_threshold", type: "uint256" }],
        name: "changeThreshold",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "dataHash", type: "bytes32" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "bytes", name: "signatures", type: "bytes" },
            { internalType: "uint256", name: "requiredSignatures", type: "uint256" },
        ],
        name: "checkNSignatures",
        outputs: [],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "dataHash", type: "bytes32" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "bytes", name: "signatures", type: "bytes" },
        ],
        name: "checkSignatures",
        outputs: [],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "prevModule", type: "address" },
            { internalType: "address", name: "module", type: "address" },
        ],
        name: "disableModule",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "domainSeparator",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "module", type: "address" }],
        name: "enableModule",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "enum Enum.Operation", name: "operation", type: "uint8" },
            { internalType: "uint256", name: "safeTxGas", type: "uint256" },
            { internalType: "uint256", name: "baseGas", type: "uint256" },
            { internalType: "uint256", name: "gasPrice", type: "uint256" },
            { internalType: "address", name: "gasToken", type: "address" },
            { internalType: "address", name: "refundReceiver", type: "address" },
            { internalType: "uint256", name: "_nonce", type: "uint256" },
        ],
        name: "encodeTransactionData",
        outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "enum Enum.Operation", name: "operation", type: "uint8" },
            { internalType: "uint256", name: "safeTxGas", type: "uint256" },
            { internalType: "uint256", name: "baseGas", type: "uint256" },
            { internalType: "uint256", name: "gasPrice", type: "uint256" },
            { internalType: "address", name: "gasToken", type: "address" },
            {
                internalType: "address payable",
                name: "refundReceiver",
                type: "address",
            },
            { internalType: "bytes", name: "signatures", type: "bytes" },
        ],
        name: "execTransaction",
        outputs: [{ internalType: "bool", name: "success", type: "bool" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "enum Enum.Operation", name: "operation", type: "uint8" },
        ],
        name: "execTransactionFromModule",
        outputs: [{ internalType: "bool", name: "success", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "enum Enum.Operation", name: "operation", type: "uint8" },
        ],
        name: "execTransactionFromModuleReturnData",
        outputs: [
            { internalType: "bool", name: "success", type: "bool" },
            { internalType: "bytes", name: "returnData", type: "bytes" },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "getChainId",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "start", type: "address" },
            { internalType: "uint256", name: "pageSize", type: "uint256" },
        ],
        name: "getModulesPaginated",
        outputs: [
            { internalType: "address[]", name: "array", type: "address[]" },
            { internalType: "address", name: "next", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getOwners",
        outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "offset", type: "uint256" },
            { internalType: "uint256", name: "length", type: "uint256" },
        ],
        name: "getStorageAt",
        outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getThreshold",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "enum Enum.Operation", name: "operation", type: "uint8" },
            { internalType: "uint256", name: "safeTxGas", type: "uint256" },
            { internalType: "uint256", name: "baseGas", type: "uint256" },
            { internalType: "uint256", name: "gasPrice", type: "uint256" },
            { internalType: "address", name: "gasToken", type: "address" },
            { internalType: "address", name: "refundReceiver", type: "address" },
            { internalType: "uint256", name: "_nonce", type: "uint256" },
        ],
        name: "getTransactionHash",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "module", type: "address" }],
        name: "isModuleEnabled",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "owner", type: "address" }],
        name: "isOwner",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "nonce",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "prevOwner", type: "address" },
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "_threshold", type: "uint256" },
        ],
        name: "removeOwner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "handler", type: "address" }],
        name: "setFallbackHandler",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "guard", type: "address" }],
        name: "setGuard",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address[]", name: "_owners", type: "address[]" },
            { internalType: "uint256", name: "_threshold", type: "uint256" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "bytes", name: "data", type: "bytes" },
            { internalType: "address", name: "fallbackHandler", type: "address" },
            { internalType: "address", name: "paymentToken", type: "address" },
            { internalType: "uint256", name: "payment", type: "uint256" },
            {
                internalType: "address payable",
                name: "paymentReceiver",
                type: "address",
            },
        ],
        name: "setup",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        name: "signedMessages",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "targetContract", type: "address" },
            { internalType: "bytes", name: "calldataPayload", type: "bytes" },
        ],
        name: "simulateAndRevert",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "prevOwner", type: "address" },
            { internalType: "address", name: "oldOwner", type: "address" },
            { internalType: "address", name: "newOwner", type: "address" },
        ],
        name: "swapOwner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    { stateMutability: "payable", type: "receive" },
];